language: node_js
node_js:
  - "8.9"
dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=8080 http://localhost &
sudo: false
before_script:
    - jdk_switcher use oraclejdk8